#cloud-config
autoinstall:
  updates: security
  apt:
    disable_components: [restricted,multiverse,universe]
    disable_suites: [backports,security,updates,main,jammy]
  identity: {hostname: zarf-games, password: $6$45rn4zLWI0EG.EIW$NP5d0VfcJNcw1n9owoKsk8PpaQ20FmHyO6CK4/yG9zXmKwgquxqZBM.qGB6WrYdv1.SX9fK7a9WKWqrFvD6m/1,
    realname: Admin, username: admin}
  refresh-installer:
    update: no
  ssh:
    allow-pw: true
    install-server: true
  storage:
    layout:
      name: lvm
  # packages:
  #  - net-tools
  late-commands:
    # - curtin in-target --target=/target -- grub-install                       # These commands are for a workaround for
    # - curtin in-target --target=/target -- sed -i 's/GRUB_CMDLINE_LINUX=""/GRUB_CMDLINE_LINUX="net.ifnames=0 biosdevname=0"/' /etc/default/grub # Make sure network interface is named eth0
    # - curtin in-target --target=/target -- update-initramfs -u -k $(uname -r) # ubuntu only booting to a GRUB cli
    # - curtin in-target --target=/target -- update-grub                        # instead of booting into the OS
    - curtin in-target --target=/target -- curl http://192.168.0.254/roles/zarf-games/job-zarf-games.sh --output /bin/firstboot.sh
    - curtin in-target --target=/target -- chmod +x /bin/firstboot.sh
    - curtin in-target --target=/target -- curl http://192.168.0.254/roles/zarf-games/runonce.service --output /etc/systemd/system/runonce.service
    - curtin in-target --target=/target -- systemctl enable runonce.service
  version: 1
# Documentation link below
# https://ubuntu.com/server/docs/install/autoinstall-reference
package_update: false
package_upgrade: false