# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"

  config.vm.provider :libvirt do |lv|
    # https://vagrant-libvirt.github.io/vagrant-libvirt/configuration.html#domain-specific-options (boot)
    lv.boot "hd" # enables boot menu (post restart)

    # https://vagrant-libvirt.github.io/vagrant-libvirt/configuration.html#usb-controller-configuration
    # we don't want slow-*ss USB 1!
    lv.usb_controller :model => "qemu-xhci"

    # https://vagrant-libvirt.github.io/vagrant-libvirt/configuration.html#usb-device-passthrough
    # lsusb: Bus 001 Device 007: ID 0781:55a5 SanDisk Corp. Cruzer U
    lv.usb :vendor => '0x0781', :product => '0x55a5'
  end

end

#
# Experiment: boot from usb.img..?
#
# Vagrant.configure("2") do |config|
#   config.vm.box = "generic/ubuntu2204"

#   config.vm.provider :libvirt do |lv|
#     # https://vagrant-libvirt.github.io/vagrant-libvirt/configuration.html#domain-specific-options (boot)
#     lv.boot = "hd" # to enable boot menu..?

#     # https://gist.github.com/mcastelino/d7477dd6183244c5fe64c17c9b4c2c88
#     lv.qemuargs :value => "-usbdevice"
#     lv.qemuargs :value => "disk:raw:usb.img"
#   end

# end
