apiVersion: apps/v1
kind: Deployment
metadata:
  name: maas
  labels:
    app: maas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maas
  template:
    metadata:
      labels:
        app: maas
    spec:
      hostNetwork: true
      containers:
        - name: maas
          image: ghcr.io/defenseunicorns/zarf-package-bare-metal:main
          command: ["/sbin/init"]
          ports:
            - name: http
              containerPort: 5240
              protocol: TCP
            - containerPort: 53
              hostPort: 53
              protocol: UDP
              name: dns-udp
            - containerPort: 53
              hostPort: 53
              protocol: TCP
              name: dns-tcp
            - containerPort: 67
              hostPort: 67
              protocol: UDP
              name: dhcp
            - containerPort: 68
              hostPort: 68
              protocol: UDP
              name: dhcp-bootp-udp
            - containerPort: 68
              hostPort: 68
              protocol: TCP
              name: dhcp-bootp-tcp
            - containerPort: 69
              hostPort: 69
              protocol: UDP
              name: tftp
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
                - NET_ADMIN
          resources:
            limits:
              cpu: "4"
              memory: "4096Mi"
          volumeMounts:
            - name: sys-fs-cgroup
              mountPath: /sys/fs/cgroup
              readOnly: false
            - name: tmpfs-tmp
              mountPath: /tmp
              readOnly: false
            - name: tmpfs-run
              mountPath: /run
              readOnly: false
            - name: tmpfs-lock
              mountPath: /run/lock
              readOnly: false
      volumes:
        - name: sys-fs-cgroup
          hostPath:
            path: /sys/fs/cgroup
        - name: tmpfs-tmp
          emptyDir:
            medium: Memory
        - name: tmpfs-run
          emptyDir:
            medium: Memory
        - name: tmpfs-lock
          emptyDir:
            medium: Memory
