apiVersion: apps/v1
kind: Deployment
metadata:
  name: maas-images
  labels:
    app: maas-images
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maas-images
  template:
    metadata:
      labels:
        app: maas-images
    spec:
      containers:
      - name: apache
        image: ghcr.io/defenseunicorns/zarf-package-bare-metal/maas-images:0.4
        ports:
        - containerPort: 80
          hostPort: 80
        resources:
          limits:
            memory: "200Mi"
            cpu: "500m"
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
      hostNetwork: true
