Vagrant.configure("2") do |config|
    config.vm.box = "generic/ubuntu2204"
    config.vm.hostname = "pxe-server"
  
    config.vm.synced_folder "./", "/vagrant", type: "rsync"
  
    # Create a private network without vagrant DHCP
    config.vm.network "private_network",
      ip: "192.168.0.254",
      libvirt__network_name: "pxe",
      libvirt__dhcp_enabled: false,
      libvirt__forward_mode: "none"
  
    # Configure VM
    config.vm.provider :libvirt do |libvirt|
      libvirt.cpu_mode = 'host-passthrough'
      libvirt.memory = '10024'
      libvirt.cpus = '8'
    end
  
    # Expect zarf binary and init package to be in same folder as Vagrantfile, then mounted to /vagrant
    config.vm.provision "shell",
    privileged: true,
    inline: <<-SHELL
      cd /root
      cp /vagrant/zarf_v0.27.1_Linux_amd64 /usr/local/bin/zarf
      cp /vagrant/zarf-init-amd64-v0.27.1.tar.zst /root/
      cp /vagrant/zarf-package-maas-amd64-0.0.4.tar.zst /root/
      # mkdir -p /root/.docker
      # cp /vagrant/config.json /root/.docker/config.json
      chmod +x /usr/local/bin/zarf
      mkdir -p /var/images
      zarf init --components=k3s --no-progress --confirm
      # zarf package deploy oci://ghcr.io/defenseunicorns/packages/maas:0.0.1-amd64 --confirm
      zarf package deploy zarf-package-maas-amd64-0.0.4.tar.zst --no-progress --confirm

      # Login to the registry
      mkdir -p ~/.docker
      REGISTRY_SECRET=$(zarf tools get-creds registry)
      AUTH=$(echo -n "zarf-push:$REGISTRY_SECRET" | base64)
      echo "{ \\"auths\\": { \\"127.0.0.1:31999\\": { \\"auth\\": \\"$AUTH\\" } } }" > ~/.docker/config.json

      # Publish every package int he current directory to the registry
      for ZARF_PACKAGE in zarf-*; do
        zarf package publish $ZARF_PACKAGE oci://127.0.0.1:31999/zarf-packages --no-progress --insecure
      done

    SHELL
  end
