apiVersion: apps/v1
kind: Deployment
metadata:
  name: zarf-pxe
spec:
  selector:
    matchLabels:
      app: zarf-pxe
  template:
    metadata:
      labels:
        app: zarf-pxe
    spec:
      containers:
      - name: zarf-pxe
        image: ghcr.io/ferrarimarco/pxe:master
        command: ["dnsmasq"]
        args: ["--no-daemon", "--dhcp-range=###ZARF_VAR_IPSTART###,###ZARF_VAR_IPEND###,###ZARF_VAR_SUBNET###"]
        volumeMounts:
          - name: tftpdir
            mountPath: /var/lib/tftpboot
          - name: dnsmasqconfig
            mountPath: /etc/dnsmasq.conf
            subPath: dnsmasq.conf
          - name: grubconfig
            mountPath: /var/lib/tftpboot/grub/grub.cfg
            subPath: grub.cfg
        resources:
          limits:
            memory: "200Mi"
            cpu: "500m"
        securityContext:
          capabilities:
            add:
              - NET_ADMIN

      - name: zarf-nginx
        image: nginx:1.23.3
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "200Mi"
            cpu: "500m"
        volumeMounts:
          - name: httpdir
            mountPath: /usr/share/nginx/html

      volumes:
        - name: tftpdir
          hostPath:
            path: /tftpboot
            type: Directory
        - name: httpdir
          hostPath:
            path: /httpboot
            type: Directory
        - name: dnsmasqconfig
          configMap:
            name: dnsmasqconfig
        - name: grubconfig
          configMap:
            name: grubconfig
      hostNetwork: true
          
