apiVersion: v1
kind: ConfigMap
metadata:
  name: games-role
data:
  meta-data: ""
  user-data: |
    #cloud-config
    autoinstall:
      updates: security
      apt:
        disable_components: [restricted,multiverse,universe]
        disable_suites: [backports,security,updates,main,jammy]
      # Password is "admin" TODO
      identity: {
        hostname: zarf-games,
        password: $6$45rn4zLWI0EG.EIW$NP5d0VfcJNcw1n9owoKsk8PpaQ20FmHyO6CK4/yG9zXmKwgquxqZBM.qGB6WrYdv1.SX9fK7a9WKWqrFvD6m/1,
        realname: Admin,
        username: admin
      }
      refresh-installer:
        update: no
      ssh:
        allow-pw: true
        install-server: true
      storage:
        layout:
          name: lvm
      late-commands:
        - curtin in-target --target=/target -- curl http://192.168.0.254/roles/zarf-games/job-zarf-games.sh --output /bin/firstboot.sh
        - curtin in-target --target=/target -- chmod +x /bin/firstboot.sh
        - curtin in-target --target=/target -- curl http://192.168.0.254/roles/zarf-games/runonce.service --output /etc/systemd/system/runonce.service
        - curtin in-target --target=/target -- systemctl enable runonce.service
      version: 1
  job-zarf-games.sh: |
    #!/bin/bash

    # Safer bash script
    set -euo pipefail

    cd /root

    wget http://192.168.0.254/zarf/zarf-games/zarf -q
    wget http://192.168.0.254/zarf/zarf-games/zarf-init-amd64-v0.27.1.tar.zst -q
    wget http://192.168.0.254/zarf/zarf-games/zarf-package-dos-games-amd64.tar.zst -q

    chmod +x ./zarf

    ./zarf init --confirm --components k3s --set K3S_ARGS=""

    ./zarf package deploy zarf-package-dos-games-amd64.tar.zst --confirm

    systemctl disable runonce.service

    rm -f /etc/systemd/runonce.service
  runonce.service: |
    [Unit]
    Description=Runonce Provisioner
    After=multi-user.target

    [Service]
    Type=simple
    User=root
    Environment="TERM=linux"
    ExecStart=/bin/firstboot.sh
    Restart=no

    [Install]
    WantedBy=multi-user.target