apiVersion: v1
kind: ConfigMap
metadata:
  name: grubconfig
data:
  grub.cfg: |
    set default="0"
    set timeout=-1

    if loadfont unicode ; then
      set gfxmode=auto
      set locale_dir=$prefix/locale
      set lang=en_US
    fi
    terminal_output gfxterm
    
    set menu_color_normal=white/black
    set menu_color_highlight=black/light-gray
    if background_color 44,0,30; then
      clear
    fi
    
    function gfxmode {
            set gfxpayload="${1}"
            if [ "${1}" = "keep" ]; then
                    set vt_handoff=vt.handoff=7
            else
                    set vt_handoff=
            fi
    }
    
    set linux_gfx_mode=keep
    
    export linux_gfx_mode
    
    menuentry 'Zarf - Games' {
            gfxmode $linux_gfx_mode
            linuxefi /init/vmlinuz root=/dev/ram0 ramdisk_size=1500000 ip=dhcp url=http://192.168.0.254/isos/ubuntu22.iso autoinstall ds=nocloud-net\;s=http://192.168.0.254/roles/zarf-games/
            initrdefi /init/initrd
    }
    
    menuentry 'Zarf - Tiny Kafka' {
            gfxmode $linux_gfx_mode
            linuxefi /init/vmlinuz root=/dev/ram0 ramdisk_size=1500000 ip=dhcp url=http://192.168.0.254/isos/ubuntu22.iso autoinstall ds=nocloud-net\;s=http://192.168.0.254/roles/zarf-tiny-kafka/
            initrdefi /init/initrd
    }