Vagrant.configure("2") do |config|
    config.vm.box = "generic/ubuntu2204"
    config.vm.hostname = "pxe-server"
  
    config.vm.synced_folder "./", "/vagrant", type: "rsync"
  
    # Create a private network without vagrant DHCP
    config.vm.network "private_network",
      ip: "192.168.0.254",
      libvirt__network_name: "pxe",
      libvirt__dhcp_enabled: false
  
    # Configure VM
    config.vm.provider :libvirt do |libvirt|
      libvirt.cpu_mode = 'host-passthrough'
      libvirt.memory = '4096'
      libvirt.cpus = '2'
    end
  
    # Expect zarf binary and init package to be in same folder as Vagrantfile, then mounted to /vagrant
    config.vm.provision "shell",
    privileged: true,
    inline: <<-SHELL
      systemctl stop systemd-resolved
      systemctl disable systemd-resolved
      unlink /etc/resolv.conf
      echo -e "nameserver 127.0.0.1\r\nnameserver 1.1.1.1\r\nnameserver 8.8.8.8" > /etc/resolv.conf
      
      # wget https://github.com/defenseunicorns/zarf/releases/download/v0.24.2/zarf_v0.24.2_Linux_amd64
      # mv zarf_v0.24.2_Linux_amd64 /usr/local/bin/zarf
      # wget https://github.com/defenseunicorns/zarf/releases/download/v0.24.2/zarf-init-amd64-v0.24.2.tar.zst
      
      cp /vagrant/zarf_v0.24.2_Linux_amd64 /usr/local/bin/zarf
      cp /vagrant/zarf-init-amd64-v0.24.2.tar.zst /home/vagrant/
      chmod +x /usr/local/bin/zarf
      mkdir /var/images
      zarf init --components=k3s,git-server --no-progress --confirm
      zarf package deploy /vagrant/zarf-package-zarf-pxe-amd64.tar.zst
    SHELL
  end
