Vagrant.configure("2") do |config|
    config.vm.box = "generic/ubuntu2204"
    config.vm.hostname = "pxe-server"
  
    config.vm.synced_folder "./", "/vagrant", type: "rsync"
  
    # Create a private network without vagrant DHCP
    config.vm.network "private_network",
      ip: "192.168.0.254",
      libvirt__network_name: "pxe",
      libvirt__dhcp_enabled: false,
      libvirt__forward_mode: "none"
  
    # Configure VM
    config.vm.provider :libvirt do |libvirt|
      libvirt.cpu_mode = 'host-passthrough'
      libvirt.memory = '4096'
      libvirt.cpus = '2'
    end
  
    # Expect zarf binary and init package to be in same folder as Vagrantfile, then mounted to /vagrant
    config.vm.provision "shell",
    privileged: true,
    inline: <<-SHELL
      cp /vagrant/zarf_v0.26.1_Linux_amd64 /usr/local/bin/zarf
      cp /vagrant/zarf-init-amd64-v0.26.1.tar.zst /home/vagrant/
      chmod +x /usr/local/bin/zarf
      mkdir -p /var/images
      zarf init --components=k3s --no-progress --confirm
      zarf package deploy /vagrant/zarf-package-zarf-pxe-amd64.tar.zst --confirm
    SHELL
  end
