name: Build MAAS Zarf Package
run-name: ${{github.actor}} is building the MAAS Zarf Package

on:
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  VERSION: 0.0.1
  
jobs:
  image-create:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./zarf-package-maas/
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Install Zarf
        uses: defenseunicorns/setup-zarf@main
        with:
          version: v0.26.1
    
      - name: Build Zarf Package
        run: zarf package create --confirm --skip-sbom -o=zarf-package-maas-amd64-${{ env.VERSION }}.tar.zst
    
      - name: Log into container registry
        uses: docker/login-action@v2
        with:
          registry: ${{env.REGISTRY}}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Push Zarf Package
        run: zarf -l debug package publish zarf-package-maas-amd64-${{ env.VERSION }}.tar.zst oci://ghcr.io/defenseunicorns/zarf-package-maas:${{ env.VERSION }}-amd64
        