name: Build MAAS Zarf Package
run-name: ${{github.actor}} is building the MAAS Zarf Package

on:
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  VERSION: 0.0.2
  
jobs:
  package-create:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./zarf-package-maas/
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Install Zarf
        uses: defenseunicorns/setup-zarf@main
        with:
          version: v0.26.1
    
      - name: Build Zarf Package
        run: |
          zarf package create --confirm --skip-sbom
          ls

      - name: Log into container registry
        uses: docker/login-action@v2
        with:
          registry: ${{env.REGISTRY}}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Push Zarf Package to OCI
        run: |
          ls
          zarf -l debug package publish ./zarf-package-maas-amd64-${{ env.VERSION }}.tar.zst oci://ghcr.io/defenseunicorns/packages
        
      - name: Create release for MAAS package
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: ${{ env.VERSION }}
          draft: false
          prerelease: true
      
      - name: Debugging
        run: |
          ls
          pwd

      - name: Upload Zarf Package to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./zarf-package-maas/zarf-package-maas-amd64-${{ env.VERSION }}.tar.zst
          asset_name: zarf-package-maas-amd64-${{ env.VERSION }}.tar.zst
          asset_content_type: application/x-tar+zstd
