name: Build MAAS Image
run-name: ${{github.actor}} is building the MAAS Container Image

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: maas
  
jobs:
  image-create:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./zarf-package-maas/region-rack-image/

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log into container registry
      uses: docker/login-action@v2
      with:
        registry: ${{env.REGISTRY}}
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Extract tags and labels
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{env.REGISTRY}}/${{env.IMAGE_NAME}}

    - name: Build Image
      uses: docker/build-push-action@v4
      with:
        context: ./zarf-package-maas/region-rack-image/
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
